name: Reusable Deployment
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifact
        required: true
        type: string

jobs:
  reusable_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name}}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & Uploading..."
 
