name: Reusable Deployment
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifact
        required: true
        type: string
    outputs:
      result:
        description: "The result of the deploy"
        value : ${{ jobs.the_reusable_deploy.outputs.theoutcome}}
    secrets:
      some-secret:
        required: true

jobs:
  the_reusable_deploy:
    outputs:
      theoutcome: ${{ steps.the-set-result-stepid.outputs.the-step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Modify Secret
        run: |
          # Modify the secret by inserting a space between each character
          SOME_SECRET="${{ secrets.some-secret }}"
          MODIFIED_SECRET=""
          for ((i=0; i<${#SOME_SECRET}; i++)); do
            MODIFIED_SECRET="${MODIFIED_SECRET}${SOME_SECRET:i:1} "
          done
          echo "Modified Secret: $MODIFIED_SECRET"
      - name: Output information
        run: echo "Deploying & Uploading..."
      - name: Set output result
        id : the-set-result-stepid
        run: echo "::set-output name=the-step-result::asuccessvalue"
